import { TicketTemplate, generateId } from './editor-types';

// Premium Dark template - based on reference design
export const premiumDarkTemplate: TicketTemplate = {
  id: 'premium-dark',
  name: 'Premium Dark',
  description: 'Elegant dark theme with gold accents and wave pattern',
  dimensions: {
    width: 90,
    height: 70,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#d4af37',
    borderOpacity: 0.6,
  },
  background: {
    type: 'image',
    color: '#0d1117',
    imageUrl: '/images/premium-bg.jpg',
    imageFit: 'cover',
    imageOpacity: 1,
    pattern: 'none',
  },
  elements: [
    {
      id: generateId(),
      type: 'text',
      position: { x: 5, y: 6 },
      size: { width: 50, height: 10 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      content: 'WiFi De Tsararano',
      textStyle: {
        fontSize: 24,
        fontWeight: 'bold',
        fontStyle: 'italic',
        textAlign: 'left',
        color: '#ffffff',
        opacity: 1,
        fontFamily: 'serif',
      },
    },
    {
      id: generateId(),
      type: 'text',
      position: { x: 5, y: 14 },
      size: { width: 30, height: 5 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      content: 'Connexion Internet',
      textStyle: {
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#d4af37',
        opacity: 0.9,
        fontFamily: 'sans',
      },
    },
    {
      id: generateId(),
      type: 'badge',
      position: { x: 75, y: 6 },
      size: { width: 20, height: 8 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      content: 'Priority',
      textStyle: {
        fontSize: 12,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#1a1a2e',
        opacity: 1,
      },
      boxStyle: {
        backgroundColor: '#d4af37',
        backgroundOpacity: 1,
        borderRadius: 6,
        borderWidth: 0,
        borderColor: 'transparent',
        borderOpacity: 0,
        padding: 10,
      },
    },
    {
      id: generateId(),
      type: 'username',
      position: { x: 5, y: 22 },
      size: { width: 45, height: 22 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: "NOM D'UTILISATEUR",
      placeholder: '{username}',
      showLabel: true,
      textStyle: {
        fontSize: 24,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#ffffff',
        opacity: 1,
      },
      boxStyle: {
        backgroundColor: '#ffffff',
        backgroundOpacity: 0.08,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ffffff',
        borderOpacity: 0.15,
        padding: 12,
        blur: 8,
      },
    },
    {
      id: generateId(),
      type: 'password',
      position: { x: 5, y: 46 },
      size: { width: 45, height: 22 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'MOT DE PASSE',
      placeholder: '{password}',
      showLabel: true,
      textStyle: {
        fontSize: 28,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#ffffff',
        opacity: 1,
      },
      boxStyle: {
        backgroundColor: '#ffffff',
        backgroundOpacity: 0.08,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ffffff',
        borderOpacity: 0.15,
        padding: 12,
        blur: 8,
      },
    },
    {
      id: generateId(),
      type: 'duration',
      position: { x: 5, y: 70 },
      size: { width: 20, height: 12 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'DUREE',
      placeholder: '{duration}',
      showLabel: true,
      textStyle: {
        fontSize: 16,
        fontWeight: 'semibold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#ffffff',
        opacity: 1,
      },
    },
    {
      id: generateId(),
      type: 'divider',
      position: { x: 28, y: 70 },
      size: { width: 0.5, height: 12 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      boxStyle: {
        backgroundColor: '#ffffff',
        backgroundOpacity: 0.3,
        borderRadius: 0,
        borderWidth: 0,
        borderColor: 'transparent',
        borderOpacity: 0,
        padding: 0,
      },
    },
    {
      id: generateId(),
      type: 'profile',
      position: { x: 32, y: 70 },
      size: { width: 20, height: 12 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'PROFIL',
      placeholder: '{profile}',
      showLabel: true,
      textStyle: {
        fontSize: 16,
        fontWeight: 'semibold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#ffffff',
        opacity: 1,
      },
    },
    {
      id: generateId(),
      type: 'qrcode',
      position: { x: 55, y: 22 },
      size: { width: 40, height: 50 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      boxStyle: {
        backgroundColor: '#ffffff',
        backgroundOpacity: 1,
        borderRadius: 16,
        borderWidth: 0,
        borderColor: 'transparent',
        borderOpacity: 0,
        padding: 16,
      },
    },
    {
      id: generateId(),
      type: 'text',
      position: { x: 55, y: 74 },
      size: { width: 40, height: 6 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      content: 'Scanner pour se connecter',
      textStyle: {
        fontSize: 11,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
        opacity: 0.8,
      },
    },
    {
      id: generateId(),
      type: 'text',
      position: { x: 55, y: 80 },
      size: { width: 40, height: 4 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      content: 'ou',
      textStyle: {
        fontSize: 10,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
        opacity: 0.6,
      },
    },
    {
      id: generateId(),
      type: 'text',
      position: { x: 55, y: 84 },
      size: { width: 40, height: 6 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      content: 'verifier le temps restant',
      textStyle: {
        fontSize: 11,
        fontWeight: 'semibold',
        fontStyle: 'italic',
        textAlign: 'center',
        color: '#ffffff',
        opacity: 0.9,
      },
    },
    {
      id: generateId(),
      type: 'url',
      position: { x: 5, y: 84 },
      size: { width: 45, height: 8 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      placeholder: '{loginUrl}',
      textStyle: {
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#ffffff',
        opacity: 0.6,
      },
    },
    {
      id: generateId(),
      type: 'contact',
      position: { x: 5, y: 92 },
      size: { width: 45, height: 6 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      content: 'Facebook: WiFi De Tsararano',
      textStyle: {
        fontSize: 11,
        fontWeight: 'semibold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#d4af37',
        opacity: 0.9,
      },
    },
    {
      id: generateId(),
      type: 'text',
      position: { x: 55, y: 92 },
      size: { width: 40, height: 6 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      content: 'a votre service 24h/24',
      textStyle: {
        fontSize: 11,
        fontWeight: 'normal',
        fontStyle: 'italic',
        textAlign: 'right',
        color: '#d4af37',
        opacity: 0.8,
      },
    },
  ],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  isBuiltIn: true,
};

// Modern Clean template
export const modernCleanTemplate: TicketTemplate = {
  id: 'modern-clean',
  name: 'Modern Clean',
  description: 'Clean and modern design with subtle gradients',
  dimensions: {
    width: 85,
    height: 55,
    borderRadius: 12,
    borderWidth: 0,
    borderColor: 'transparent',
    borderOpacity: 0,
  },
  background: {
    type: 'gradient',
    color: '#667eea',
    gradientFrom: '#667eea',
    gradientTo: '#764ba2',
    gradientAngle: 135,
    imageFit: 'cover',
    imageOpacity: 1,
  },
  elements: [
    {
      id: generateId(),
      type: 'text',
      position: { x: 6, y: 8 },
      size: { width: 60, height: 12 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      content: 'WiFi Access',
      textStyle: {
        fontSize: 28,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#ffffff',
        opacity: 1,
        fontFamily: 'sans',
      },
    },
    {
      id: generateId(),
      type: 'username',
      position: { x: 6, y: 28 },
      size: { width: 42, height: 28 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'Username',
      placeholder: '{username}',
      showLabel: true,
      textStyle: {
        fontSize: 22,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#ffffff',
        opacity: 1,
      },
      boxStyle: {
        backgroundColor: '#ffffff',
        backgroundOpacity: 0.15,
        borderRadius: 10,
        borderWidth: 0,
        borderColor: 'transparent',
        borderOpacity: 0,
        padding: 14,
      },
    },
    {
      id: generateId(),
      type: 'password',
      position: { x: 6, y: 60 },
      size: { width: 42, height: 28 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'Password',
      placeholder: '{password}',
      showLabel: true,
      textStyle: {
        fontSize: 22,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#ffffff',
        opacity: 1,
      },
      boxStyle: {
        backgroundColor: '#ffffff',
        backgroundOpacity: 0.15,
        borderRadius: 10,
        borderWidth: 0,
        borderColor: 'transparent',
        borderOpacity: 0,
        padding: 14,
      },
    },
    {
      id: generateId(),
      type: 'qrcode',
      position: { x: 54, y: 24 },
      size: { width: 40, height: 65 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      boxStyle: {
        backgroundColor: '#ffffff',
        backgroundOpacity: 1,
        borderRadius: 12,
        borderWidth: 0,
        borderColor: 'transparent',
        borderOpacity: 0,
        padding: 12,
      },
    },
  ],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  isBuiltIn: true,
};

// Minimalist template
export const minimalistTemplate: TicketTemplate = {
  id: 'minimalist',
  name: 'Minimalist',
  description: 'Simple and elegant minimalist design',
  dimensions: {
    width: 80,
    height: 50,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderOpacity: 1,
  },
  background: {
    type: 'solid',
    color: '#ffffff',
    imageFit: 'cover',
    imageOpacity: 1,
  },
  elements: [
    {
      id: generateId(),
      type: 'text',
      position: { x: 6, y: 10 },
      size: { width: 50, height: 10 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      content: 'WiFi',
      textStyle: {
        fontSize: 20,
        fontWeight: 'medium',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#111827',
        opacity: 1,
        fontFamily: 'sans',
        letterSpacing: 2,
      },
    },
    {
      id: generateId(),
      type: 'username',
      position: { x: 6, y: 28 },
      size: { width: 45, height: 25 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'User',
      placeholder: '{username}',
      showLabel: true,
      textStyle: {
        fontSize: 18,
        fontWeight: 'semibold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#111827',
        opacity: 1,
      },
    },
    {
      id: generateId(),
      type: 'password',
      position: { x: 6, y: 58 },
      size: { width: 45, height: 25 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'Pass',
      placeholder: '{password}',
      showLabel: true,
      textStyle: {
        fontSize: 18,
        fontWeight: 'semibold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#111827',
        opacity: 1,
      },
    },
    {
      id: generateId(),
      type: 'qrcode',
      position: { x: 58, y: 15 },
      size: { width: 36, height: 70 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      boxStyle: {
        backgroundColor: '#f9fafb',
        backgroundOpacity: 1,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderOpacity: 1,
        padding: 10,
      },
    },
  ],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  isBuiltIn: true,
};

// Ocean Blue template
export const oceanBlueTemplate: TicketTemplate = {
  id: 'ocean-blue',
  name: 'Ocean Blue',
  description: 'Calming ocean-inspired blue theme',
  dimensions: {
    width: 85,
    height: 60,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#0ea5e9',
    borderOpacity: 0.5,
  },
  background: {
    type: 'gradient',
    color: '#0c4a6e',
    gradientFrom: '#0c4a6e',
    gradientTo: '#075985',
    gradientAngle: 180,
    imageFit: 'cover',
    imageOpacity: 1,
    pattern: 'waves',
    patternOpacity: 0.1,
  },
  elements: [
    {
      id: generateId(),
      type: 'text',
      position: { x: 5, y: 6 },
      size: { width: 55, height: 10 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      content: 'Connect to WiFi',
      textStyle: {
        fontSize: 22,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#ffffff',
        opacity: 1,
        fontFamily: 'sans',
      },
    },
    {
      id: generateId(),
      type: 'badge',
      position: { x: 75, y: 6 },
      size: { width: 20, height: 8 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      content: 'Premium',
      textStyle: {
        fontSize: 10,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#0c4a6e',
        opacity: 1,
      },
      boxStyle: {
        backgroundColor: '#38bdf8',
        backgroundOpacity: 1,
        borderRadius: 20,
        borderWidth: 0,
        borderColor: 'transparent',
        borderOpacity: 0,
        padding: 8,
      },
    },
    {
      id: generateId(),
      type: 'username',
      position: { x: 5, y: 22 },
      size: { width: 50, height: 22 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'USERNAME',
      placeholder: '{username}',
      showLabel: true,
      textStyle: {
        fontSize: 22,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#ffffff',
        opacity: 1,
      },
      boxStyle: {
        backgroundColor: '#0ea5e9',
        backgroundOpacity: 0.2,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#38bdf8',
        borderOpacity: 0.3,
        padding: 12,
      },
    },
    {
      id: generateId(),
      type: 'password',
      position: { x: 5, y: 48 },
      size: { width: 50, height: 22 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'PASSWORD',
      placeholder: '{password}',
      showLabel: true,
      textStyle: {
        fontSize: 22,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#ffffff',
        opacity: 1,
      },
      boxStyle: {
        backgroundColor: '#0ea5e9',
        backgroundOpacity: 0.2,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#38bdf8',
        borderOpacity: 0.3,
        padding: 12,
      },
    },
    {
      id: generateId(),
      type: 'duration',
      position: { x: 5, y: 76 },
      size: { width: 25, height: 16 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'DURATION',
      placeholder: '{duration}',
      showLabel: true,
      textStyle: {
        fontSize: 14,
        fontWeight: 'semibold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#38bdf8',
        opacity: 1,
      },
    },
    {
      id: generateId(),
      type: 'profile',
      position: { x: 32, y: 76 },
      size: { width: 25, height: 16 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'PLAN',
      placeholder: '{profile}',
      showLabel: true,
      textStyle: {
        fontSize: 14,
        fontWeight: 'semibold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#38bdf8',
        opacity: 1,
      },
    },
    {
      id: generateId(),
      type: 'qrcode',
      position: { x: 60, y: 22 },
      size: { width: 35, height: 58 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      boxStyle: {
        backgroundColor: '#ffffff',
        backgroundOpacity: 1,
        borderRadius: 12,
        borderWidth: 0,
        borderColor: 'transparent',
        borderOpacity: 0,
        padding: 10,
      },
    },
  ],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  isBuiltIn: true,
};

// Sunset Warm template
export const sunsetWarmTemplate: TicketTemplate = {
  id: 'sunset-warm',
  name: 'Sunset Warm',
  description: 'Warm sunset gradient with modern typography',
  dimensions: {
    width: 90,
    height: 55,
    borderRadius: 16,
    borderWidth: 0,
    borderColor: 'transparent',
    borderOpacity: 0,
  },
  background: {
    type: 'gradient',
    color: '#f97316',
    gradientFrom: '#dc2626',
    gradientTo: '#f97316',
    gradientAngle: 45,
    imageFit: 'cover',
    imageOpacity: 1,
  },
  elements: [
    {
      id: generateId(),
      type: 'text',
      position: { x: 5, y: 8 },
      size: { width: 90, height: 14 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      content: 'HOTSPOT ACCESS',
      textStyle: {
        fontSize: 32,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
        opacity: 1,
        fontFamily: 'sans',
        letterSpacing: 4,
      },
    },
    {
      id: generateId(),
      type: 'username',
      position: { x: 5, y: 30 },
      size: { width: 42, height: 30 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'USER ID',
      placeholder: '{username}',
      showLabel: true,
      textStyle: {
        fontSize: 24,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
        opacity: 1,
      },
      boxStyle: {
        backgroundColor: '#000000',
        backgroundOpacity: 0.2,
        borderRadius: 12,
        borderWidth: 0,
        borderColor: 'transparent',
        borderOpacity: 0,
        padding: 16,
      },
    },
    {
      id: generateId(),
      type: 'password',
      position: { x: 53, y: 30 },
      size: { width: 42, height: 30 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'PASSWORD',
      placeholder: '{password}',
      showLabel: true,
      textStyle: {
        fontSize: 24,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
        opacity: 1,
      },
      boxStyle: {
        backgroundColor: '#000000',
        backgroundOpacity: 0.2,
        borderRadius: 12,
        borderWidth: 0,
        borderColor: 'transparent',
        borderOpacity: 0,
        padding: 16,
      },
    },
    {
      id: generateId(),
      type: 'duration',
      position: { x: 5, y: 68 },
      size: { width: 30, height: 22 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      label: 'Valid For',
      placeholder: '{duration}',
      showLabel: true,
      textStyle: {
        fontSize: 18,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
        opacity: 1,
      },
    },
    {
      id: generateId(),
      type: 'qrcode',
      position: { x: 65, y: 62 },
      size: { width: 30, height: 32 },
      rotation: 0,
      visible: true,
      locked: false,
      zIndex: 10,
      boxStyle: {
        backgroundColor: '#ffffff',
        backgroundOpacity: 1,
        borderRadius: 8,
        borderWidth: 0,
        borderColor: 'transparent',
        borderOpacity: 0,
        padding: 8,
      },
    },
  ],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  isBuiltIn: true,
};

// Export all built-in templates
export const builtInTemplates: TicketTemplate[] = [
  premiumDarkTemplate,
  modernCleanTemplate,
  minimalistTemplate,
  oceanBlueTemplate,
  sunsetWarmTemplate,
];

// Create a blank template
export function createBlankTemplate(): TicketTemplate {
  return {
    id: generateId(),
    name: 'Custom Template',
    description: 'Your custom ticket design',
    dimensions: {
      width: 85,
      height: 55,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#e5e7eb',
      borderOpacity: 1,
    },
    background: {
      type: 'solid',
      color: '#ffffff',
      imageFit: 'cover',
      imageOpacity: 1,
    },
    elements: [],
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isBuiltIn: false,
  };
}

// Clone a template
export function cloneTemplate(template: TicketTemplate): TicketTemplate {
  return {
    ...template,
    id: generateId(),
    name: `${template.name} (Copy)`,
    elements: template.elements.map(el => ({
      ...el,
      id: generateId(),
    })),
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isBuiltIn: false,
  };
}
